name: Custom GitHub Runners 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: echo
        run: echo "Hello cloud gurus"

    
